[project]
name = "lanna"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "colorama>=0.4.6",
    "onnx>=1.22.0",
    "onnxruntime>=1.27.0",
    "sentencepiece>=0.2.2",
    "torch>=2.13.0",
    "tqdm>=4.70.0",
]

[tool.uv.workspace]
members = [
    "gutenberg",
    "server",
]
